// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: deck_cards.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDeckCard = `-- name: CreateDeckCard :one
INSERT INTO deck_cards (deck_id, card_code) VALUES ($1, $2) RETURNING deck_id, card_code, drawn, created_at, updated_at
`

type CreateDeckCardParams struct {
	DeckID   uuid.UUID
	CardCode string
}

func (q *Queries) CreateDeckCard(ctx context.Context, arg CreateDeckCardParams) (DeckCard, error) {
	row := q.db.QueryRowContext(ctx, createDeckCard, arg.DeckID, arg.CardCode)
	var i DeckCard
	err := row.Scan(
		&i.DeckID,
		&i.CardCode,
		&i.Drawn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
