// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: decks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (id, shuffled, remaining) VALUES ($1, $2, $3) RETURNING id, shuffled, remaining, created_at, updated_at
`

type CreateDeckParams struct {
	ID        uuid.UUID
	Shuffled  bool
	Remaining int32
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRowContext(ctx, createDeck, arg.ID, arg.Shuffled, arg.Remaining)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Shuffled,
		&i.Remaining,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
