version: "3"

services:
  app:
    build: .
    ports:
      - "8500:8080"
    depends_on:
      - db
    env_file:
      - .env
    command: ["./main"]

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deck 
    ports:
      - "54322:5432"
