version: "3"

services:
  app:
    build: .
    ports:
      - "8600:8080"
    depends_on:
      - db
    env_file:
      - .env.test
    command: ["./main"]
    restart: on-failure

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_deck
    ports:
      - "54323:5432"
